#!/usr/bin/env bash
# =============================================================================
# setup-env.sh — Ariyalur Geology: Environment Validation & Local Dev Setup
# =============================================================================
# Usage:
#   chmod +x setup-env.sh
#   ./setup-env.sh [--create-env] [--test-api] [--full] [--help]
#
# Options:
#   --create-env   (Re-)create backend/.env from interactive prompts
#   --test-api     Test live API connectivity after env is set
#   --full         Run all checks (equivalent to --create-env --test-api)
#   --help         Show this help message
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${BLUE}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
step()    { echo -e "\n${BOLD}${CYAN}===> $*${RESET}"; }

CREATE_ENV=false
TEST_API=false

for arg in "$@"; do
  case "$arg" in
    --create-env) CREATE_ENV=true ;;
    --test-api)   TEST_API=true ;;
    --full)       CREATE_ENV=true; TEST_API=true ;;
    --help)
      sed -n '2,13p' "$0" | sed 's/^# //'
      exit 0
      ;;
    *) error "Unknown option: $arg"; exit 1 ;;
  esac
done

# ── banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}${CYAN}"
echo "  Ariyalur Geology — Environment Setup & Validation"
echo -e "${RESET}"

# ── helper: prompt with default ───────────────────────────────────────────────
prompt_value() {
  local label="$1" default="$2" var_name="$3"
  if [[ -n "$default" ]]; then
    read -rp "  ${label} [${default}]: " value
    value="${value:-$default}"
  else
    read -rp "  ${label}: " value
  fi
  printf -v "$var_name" '%s' "$value"
}

# ── 1. create / update .env ───────────────────────────────────────────────────
step "1/5 — .env file"

ENV_FILE="backend/.env"

if $CREATE_ENV || [[ ! -f "$ENV_FILE" ]]; then
  echo ""
  info "You will be prompted for each required value."
  info "Press ENTER to accept the default (shown in brackets)."
  echo ""

  # Supabase
  echo -e "  ${BOLD}Supabase credentials${RESET} (get from https://supabase.com → Project → Settings → API)"
  prompt_value "SUPABASE_URL" "https://YOUR_PROJECT_ID.supabase.co" SUPABASE_URL
  prompt_value "SUPABASE_SERVICE_ROLE_KEY" "" SUPABASE_SERVICE_ROLE_KEY

  # Server
  echo ""
  echo -e "  ${BOLD}Server configuration${RESET}"
  prompt_value "PORT" "8080" PORT
  prompt_value "NODE_ENV" "development" NODE_ENV
  prompt_value "CORS_ORIGIN" "http://localhost:3000,https://natswebsite.com" CORS_ORIGIN

  # Storage
  echo ""
  echo -e "  ${BOLD}Storage configuration${RESET}"
  prompt_value "SUPABASE_STORAGE_BUCKET" "fossil-images" SUPABASE_STORAGE_BUCKET
  prompt_value "MAX_FILE_SIZE_MB" "10" MAX_FILE_SIZE_MB

  # Email (optional)
  echo ""
  echo -e "  ${BOLD}Email notifications${RESET} (optional — press ENTER to skip)"
  prompt_value "SMTP_HOST" "smtp.gmail.com" SMTP_HOST
  prompt_value "SMTP_PORT" "587" SMTP_PORT
  prompt_value "SMTP_USER" "" SMTP_USER
  prompt_value "SMTP_PASS" "" SMTP_PASS
  prompt_value "NOTIFY_EMAIL" "" NOTIFY_EMAIL

  # Write file
  mkdir -p backend
  cat > "$ENV_FILE" <<ENVFILE
# Generated by setup-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE — it is listed in backend/.gitignore

# ── Supabase ──────────────────────────────────────────────────────────────────
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

# ── Server ────────────────────────────────────────────────────────────────────
PORT=${PORT}
NODE_ENV=${NODE_ENV}
CORS_ORIGIN=${CORS_ORIGIN}

# ── Storage ───────────────────────────────────────────────────────────────────
SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET}
MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB}

# ── Email (optional) ──────────────────────────────────────────────────────────
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
NOTIFY_EMAIL=${NOTIFY_EMAIL}
ENVFILE

  success "backend/.env written"
else
  info "backend/.env already exists — use --create-env to recreate"
fi

# ── 2. validate credentials format ───────────────────────────────────────────
step "2/5 — Validating credential format"

# Source the env file
if [[ -f "$ENV_FILE" ]]; then
  # Load variables (skip comment/blank lines)
  set -a
  # shellcheck disable=SC1090
  source <(grep -v '^\s*#' "$ENV_FILE" | grep -v '^\s*$')
  set +a
else
  error "backend/.env not found. Run with --create-env first."
  exit 1
fi

VALIDATION_PASS=true

# Supabase URL format
if [[ "${SUPABASE_URL:-}" =~ ^https://[a-z0-9]+\.supabase\.co$ ]]; then
  success "SUPABASE_URL format valid"
elif [[ "${SUPABASE_URL:-}" == "https://YOUR_PROJECT_ID.supabase.co" ]]; then
  error "SUPABASE_URL still contains placeholder — update backend/.env"
  VALIDATION_PASS=false
else
  warn "SUPABASE_URL format unexpected: ${SUPABASE_URL:-<empty>}"
fi

# Service role key (should be a long JWT)
if [[ "${SUPABASE_SERVICE_ROLE_KEY:-}" =~ ^eyJ ]]; then
  success "SUPABASE_SERVICE_ROLE_KEY format valid (JWT detected)"
elif [[ -z "${SUPABASE_SERVICE_ROLE_KEY:-}" ]]; then
  error "SUPABASE_SERVICE_ROLE_KEY is empty — update backend/.env"
  VALIDATION_PASS=false
else
  warn "SUPABASE_SERVICE_ROLE_KEY may be invalid (expected JWT starting with 'eyJ')"
fi

# PORT
if [[ "${PORT:-8080}" =~ ^[0-9]+$ ]] && (( PORT >= 1 && PORT <= 65535 )); then
  success "PORT=${PORT} is valid"
else
  warn "PORT value looks invalid: ${PORT:-<empty>}"
fi

# CORS_ORIGIN
if [[ -n "${CORS_ORIGIN:-}" ]]; then
  success "CORS_ORIGIN configured: ${CORS_ORIGIN}"
else
  warn "CORS_ORIGIN is empty"
fi

# ── 3. test Supabase API connectivity ─────────────────────────────────────────
step "3/5 — Supabase API connectivity"

if $TEST_API && [[ "${SUPABASE_URL:-}" != "https://YOUR_PROJECT_ID.supabase.co" ]]; then
  info "Testing Supabase REST API endpoint..."

  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
    --connect-timeout 10 \
    -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
    "${SUPABASE_URL}/rest/v1/") || true

  case "$HTTP_CODE" in
    200) success "Supabase REST API reachable (HTTP 200)" ;;
    401) error  "Supabase API returned 401 — check SUPABASE_SERVICE_ROLE_KEY" ;;
    404) warn   "Supabase API returned 404 — check SUPABASE_URL" ;;
    000) error  "Could not connect to Supabase (DNS/network error)" ;;
    *)   warn   "Supabase API returned HTTP ${HTTP_CODE}" ;;
  esac

  # Test storage bucket
  info "Testing Supabase Storage bucket '${SUPABASE_STORAGE_BUCKET}'..."
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
    --connect-timeout 10 \
    -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
    "${SUPABASE_URL}/storage/v1/bucket/${SUPABASE_STORAGE_BUCKET}") || true

  case "$HTTP_CODE" in
    200) success "Storage bucket '${SUPABASE_STORAGE_BUCKET}' exists and accessible" ;;
    404) warn   "Storage bucket '${SUPABASE_STORAGE_BUCKET}' not found — create it in Supabase dashboard" ;;
    401) error  "Unauthorised — check SUPABASE_SERVICE_ROLE_KEY" ;;
    *)   warn   "Storage bucket check returned HTTP ${HTTP_CODE}" ;;
  esac

  # Test table: registrations
  info "Testing 'registrations' table..."
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
    --connect-timeout 10 \
    -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
    "${SUPABASE_URL}/rest/v1/registrations?limit=1") || true

  case "$HTTP_CODE" in
    200) success "'registrations' table accessible" ;;
    404) warn   "'registrations' table not found — run DB migration" ;;
    401) error  "Unauthorised accessing 'registrations' table" ;;
    *)   warn   "'registrations' table check returned HTTP ${HTTP_CODE}" ;;
  esac

  # Test table: fossil_details
  info "Testing 'fossil_details' table..."
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
    --connect-timeout 10 \
    -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
    "${SUPABASE_URL}/rest/v1/fossil_details?limit=1") || true

  case "$HTTP_CODE" in
    200) success "'fossil_details' table accessible" ;;
    404) warn   "'fossil_details' table not found — run DB migration" ;;
    401) error  "Unauthorised accessing 'fossil_details' table" ;;
    *)   warn   "'fossil_details' table check returned HTTP ${HTTP_CODE}" ;;
  esac

else
  if ! $TEST_API; then
    info "API connectivity test skipped (use --test-api or --full to enable)"
  else
    warn "Supabase URL is still a placeholder — skipping API test"
  fi
fi

# ── 4. local development setup ────────────────────────────────────────────────
step "4/5 — Local development setup"

info "Checking local dev prerequisites..."

# node_modules
if [[ -d "backend/node_modules" ]]; then
  success "backend/node_modules installed"
else
  info "Installing npm dependencies..."
  (cd backend && npm install --loglevel=warn)
  success "npm dependencies installed"
fi

# Check for server.js
if [[ -f "backend/server.js" ]]; then
  success "backend/server.js present"
else
  warn "backend/server.js not found — backend not yet scaffolded"
  info "Refer to PIPELINE_GUIDE.md for the full backend structure"
fi

# ── 5. summary ────────────────────────────────────────────────────────────────
step "5/5 — Summary"

if $VALIDATION_PASS; then
  success "Environment validated successfully"
else
  warn "Validation completed with warnings — fix errors before deploying"
fi

echo ""
echo -e "  ${BOLD}Quick start:${RESET}"
echo -e "  cd backend && npm start     # start the API server on port ${PORT:-8080}"
echo -e "  cd backend && npm test      # run the test suite"
echo -e "  ./verify-deployment.sh      # run full deployment verification"
echo ""
