-- Backend schema for registration and fossil submission forms

CREATE TABLE IF NOT EXISTS public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    institution TEXT,
    purpose TEXT,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.fossil_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fossil_name TEXT NOT NULL,
    genus_species TEXT,
    formation TEXT,
    locality TEXT,
    age TEXT,
    classification TEXT,
    description TEXT,
    collector_name TEXT NOT NULL,
    collector_email TEXT,
    field_number TEXT,
    image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'pending',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fossil_details ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can insert registrations" ON public.registrations;
CREATE POLICY "Public can insert registrations"
    ON public.registrations FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Public can insert fossil details" ON public.fossil_details;
CREATE POLICY "Public can insert fossil details"
    ON public.fossil_details FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Public can read approved fossils" ON public.fossil_details;
CREATE POLICY "Public can read approved fossils"
    ON public.fossil_details FOR SELECT
    TO anon, authenticated
    USING (status = 'approved');

INSERT INTO storage.buckets (id, name, public)
VALUES ('fossil-images', 'fossil-images', true)
ON CONFLICT (id) DO NOTHING;
